### ISSUE TITLE
Custom Port for web-admin

### ISSUE THREAD

**Issue by primoashbee** [h-mdm/remote-control#24]
Instead of using port ```:80``` I want to forward to ```:8000``` and for the ssl from ```:443``` to ```:8443```.

How can i change these from the configurations that on this package.

Thanks

**Comment by h-mdm** [comment]
Tomcat works on ports 8080 and 8443 by default. You can set up port redirection on a firewall, or by iptables. See details here: https://qa.h-mdm.com/1533/
