### ISSUE TITLE
Issues operating screen-sharing with recent browser versions

### ISSUE THREAD

**Issue by BamBalaam** [h-mdm/remote-control#25]
Hi Team,

We've been testing various things around remote-control and your android application for a while. Recently we've encountered issues with screen-sharing (control seems to be enabled since events are received by the device, it's the viewer that fails).

We first noticed the issue while testing with our own server deployment + version of Android application:

- Web-Admin running and working fine on Firefox 88 and MacOS 10.15
- Firefox upgraded to version 96, screen-sharing on the web-admin failed
- Firefox downgraded to version 88, screen-sharing worked again

Worried that our deployment scripts broke something, we tested with your default server and app and found the same issues. For example:

- Firefox 96.0.2 + Linux: screen-sharing not working
- Chromium Version 97.0.4692.99 (Official Build) Arch Linux (64-bit) + Linux: screen-sharing not working

There seems to be something, among new-ish browser stacks, that messes with webRTC protocols.

Do you have any insight? We can provide further information if needed, please tell us what you would need to diagnose this issue better.

Kind regards,
@bambalaam and @bparmentier

**Comment by h-mdm** [comment]
I just checked Headwind Remote on Firefox 96.0.2 (64-bit) on Windows, and it works well.

Looks like the issue is related to Linux OS.

We will check it out and I will let you know.

**Comment by bparmentier** [comment]
Thank your for your quick reply.

We're testing Headwind Remote right now with a Pixel 6 (Android 12) and various browsers on Windows 10:

- Firefox 96.0.2 (64-bit): white screen
- Edge 97.0.1072.69 (64-bit): grey screen with "loading dots"
- Chrome 97.0.4692.99 (64-bit): grey screen with "loading dots"

Could it be a network configuration issue?

**Comment by h-mdm** [comment]
Headwind Remote should work on Google Pixel (Android 12). At least, it has been tested on Pixel 5. 

Yes, that could be a network configuration issue. Also, please check that you've set the parameter "Show flashing dot while sharing". This flashing dot requires "Draw on top" permission, it generates the screencast network traffic so a static screen is displayed without delays.

**Comment by bparmentier** [comment]
I confirm that I enabled the "Show flashing dot while sharing" option as you can see on the following screenshot:

<img src="https://user-images.githubusercontent.com/2833843/151347546-d68027c7-fe06-48bd-a83b-d91423f86ed7.png"  width=250>

Here is a screenshot of web-admin (https://srv.headwind-remote.com/web-admin/) trying to load the image indefinitely in Chrome on Windows:

![headwind_remote_webadmin_windows10_chrome97_loading_dots](https://user-images.githubusercontent.com/2833843/151347775-2882f6ae-6074-4d93-bf6d-6c7421213beb.png)

**Comment by BamBalaam** [comment]
Investigation done by @kaygenzo

On MacOS Catalina 10.15.6:

- On Firefox Versions 95.0 through 95.0b12 (last beta before Version 96) the web-admin is working fine.
- On Firefox Version 96.0, it doesn't work. It sometimes displays an image, but not a regular remote viewing.

He further investigated and read the changelogs and release notes Firefox released:

- [Developer changelog](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/96)
- [Commercial changelog](https://www.mozilla.org/en-US/firefox/96.0/releasenotes/)

Both of these indicate recent changes to WebRTC libraries.

This Google group ( [link](https://groups.google.com/g/discuss-webrtc/c/pkAtJEF_unM?pli=1) ) discusses what were at the time "upcoming changes".

All tickets linked there are duplicates and lead to one single resolved ticket in the Firefox bug tracker ( [link](https://bugzilla.mozilla.org/show_bug.cgi?id=1654112) ).

This ticket seems to be merged on firefox96 branch.

All of this information indicates major changes in how Firefox's stack handles WebRTC. You mentioned that it seems contained to Unix-based systems only, which could be a possibility, but we've found counter-examples. Also, this is all the information we've found for Firefox, but we've found similar issues with other browsers.

Are you planning to run a deeper investigation? It seems like a pretty broad and critical bug that impacts the whole product.

**Comment by BamBalaam** [comment]
@h-mdm follow-up tests by @kaygenzo on Windows 10

Chrome 97.0.4692.99 => Working
Edge 97.0.1072.76 => Working
Firefox 96.0.3 => Not working well

Might support the theory that the issue is mostly on Firefox, but it disputes the fact that it works fine on Windows.

**Comment by h-mdm** [comment]
Yes, we are planning to run a deeper investigation, but we are unable to reproduce this issue. Perhaps the issue only arises for certain device models.

**Comment by BamBalaam** [comment]
The common thing between the devices we tested is Android, but hardware-wise they're all different. We've encountered the issue so far:

- On a Pixel 6 (Android 12)
- On a Xiaomi Redmi Note 9 Pro (Android 11)
- On proprietary hardware (Android 8)

**Comment by BamBalaam** [comment]
> Yes, we are planning to run a deeper investigation, but we are unable to reproduce this issue. Perhaps the issue only arises for certain device models.

Any findings @h-mdm ? :) 

We might have an hint, but we're grasping at straws, there is a lot of unpredictability in all the tests results we're seeing. We are seeing very different results depending on the hardware setup we have.

Could you please re-test any OS you have + Firefox 96+, while using hardware which has no dedicated graphics card (or disabling hardware acceleration on the browser). We're able to reproduce the issue several times, but not on 100% of the setups we've tested.

**Comment by BamBalaam** [comment]
We fixed the issue locally.

**Comment by HT13457** [comment]
@BamBalaam If you don't mind me asking, what exactly have you done to fix the issue? My team is also currently grappling with this issue, but we haven't found a working solution so far. So we really would appreciate a little input. Thanks!
