### ISSUE TITLE
Starting Headwind Remot fialed

### ISSUE THREAD

**Issue by liujie12** [h-mdm/remote-control#33]
fatal: [localhost]: FAILED! => {"changed": false, "errors": ["ERROR: for remote-control_nginx_1  Cannot start service nginx: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/opt/remote-control/deploy/dist/conf/nginx/nginx.conf\" to rootfs at \"/etc/nginx/nginx.conf\": mount /opt/remote-control/deploy/dist/conf/nginx/nginx.conf:/etc/nginx/nginx.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type"], "module_stderr": "Starting remote-control_nginx_1 ... \nCreating remote-control_janus_1 ... \n\u001b[2A\u001b[2K\nStarting remote-control_nginx_1 ... \n\u001b[2B\nERROR: for remote-control_nginx_1  Cannot start service nginx: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/opt/remote-control/deploy/dist/conf/nginx/nginx.conf\" to rootfs at \"/etc/nginx/nginx.conf\": mount /opt/remote-control/deploy/dist/conf/nginx/nginx.conf:/etc/nginx/nginx.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type\n\u001b[1A\u001b[2K\nCreating remote-control_janus_1 ... \n\u001b[1B", "module_stdout": "v1.4.0: Pulling from certbot/certbot\nDigest: sha256:d0f6d1c43584e4dfdfe08ddc949cf40e7b56b316d03f36b4b2e436ad1e2d4c39\nStatus: Downloaded newer image for certbot/certbot:v1.4.0\n0.12.3: Pulling from headwindmdm/janus-gateway\nDigest: sha256:a5ec39f3c51ea65788f9e7b16c04d12179caa1f93d74d6495d2476561ec3e370\nStatus: Downloaded newer image for headwindmdm/janus-gateway:0.12.3\n", "msg": "Error starting project Encountered errors while bringing up the project."}

**Comment by h-mdm** [comment]
Sometimes Ansible mistakenly creates subdirectories instead of files in the deploy/dist directory (the reason is unknown).

The solution would be:
1. Preserve the config.yaml file (since you've already configured it)
2. Delete the whole remote-control directory
3. Re-create it from the archive (or from github)
4. Copy the config.yaml file back into the directory
5. Run the installer command: bash ./install.sh
