### ISSUE TITLE
Ubuntu 20.04 install fialed

### ISSUE THREAD

**Issue by liujie12** [h-mdm/remote-control#35]
TASK [(Re)Starting Headwind Remote] *************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "Starting remote-control_nginx_1 ... \n\u001b[1A\u001b[2K\nStarting remote-control_nginx_1 ... \n\u001b[1B", "module_stdout": "", "msg": "Error starting project Encountered errors while bringing up the project."}

TASK [Download docker-compose] ******************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: socket.timeout: The read operation timed out
fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 3, "msg": "failed to create temporary content file: The read operation timed out"}

**Comment by h-mdm** [comment]
This is a problem accessing the docker-compose installer on the Internet (from github.com). Make sure your Internet connection is not blocking github.com.
