### ISSUE TITLE
janus container restarting

### ISSUE THREAD

**Issue by liujie12** [h-mdm/remote-control#36]
janus_1    | Janus commit: 1c4b1106867ffc4f49a01df02cb785996ca4fa0b
janus_1    | Compiled on:  Tue Jun 21 04:59:10 UTC 2022
janus_1    | 
janus_1    | Logger plugins folder: /usr/local/lib/janus/loggers
janus_1    | [WARN] 	Couldn't access logger plugins folder...
janus_1    | ---------------------------------------------------
janus_1    |   Starting Meetecho Janus (WebRTC Server) v0.12.3
janus_1    | ---------------------------------------------------
janus_1    | 
janus_1    | Checking command line arguments...
janus_1    | [janus.jcfg]
janus_1    |     general: {
janus_1    |         configs_folder: /usr/local/etc/janus
janus_1    |         plugins_folder: /usr/local/lib/janus/plugins
janus_1    |         transports_folder: /usr/local/lib/janus/transports
janus_1    |         events_folder: /usr/local/lib/janus/events
janus_1    |         loggers_folder: /usr/local/lib/janus/loggers
janus_1    |         debug_level: 5
janus_1    |         debug_timestamps: true
janus_1    |         debug_colors: true
janus_1    |         api_secret: uacMZZm7
janus_1    |         admin_secret: Z9A5Z8HUetTpWhV
janus_1    |         protected_folders: [
janus_1    |             /bin
janus_1    |             /boot
janus_1    |             /dev
janus_1    |             /etc
janus_1    |             /initrd
janus_1    |             /lib
janus_1    |             /lib32
janus_1    |             /lib64
janus_1    |             /proc
janus_1    |             /sbin
janus_1    |             /sys
janus_1    |             /usr
janus_1    |             /var
janus_1    |             /usr/local/bin
janus_1    |             /usr/local/etc
janus_1    |             /usr/local/include
janus_1    |             /usr/local/lib
janus_1    |             /usr/local/lib32
janus_1    |             /usr/local/lib64
janus_1    |             /usr/local/sbin
janus_1    |         ]
janus_1    |     }
janus_1    |     certificates: {
janus_1    |         cert_pem: /etc/letsencrypt/live/janus.build110.com/fullchain.pem
janus_1    |         cert_key: /etc/letsencrypt/live/janus.build110.com/privkey.pem
janus_1    |         dtls_accept_selfsigned: true
janus_1    |     }
janus_1    |     media: {
janus_1    |         rtp_port_range: 10000-10500
janus_1    |     }
janus_1    |     nat: {
janus_1    |         nice_debug: false
janus_1    |         ice_ignore_list: vmnet
janus_1    |     }
janus_1    |     plugins: {
janus_1    |     }
janus_1    |     transports: {
janus_1    |     }
janus_1    |     loggers: {
janus_1    |     }
janus_1    |     events: {
janus_1    |     }
janus_1    | Debug/log level is 5
janus_1    | Debug/log timestamps are enabled
janus_1    | Debug/log colors are enabled
janus_1    | [Mon Jul 18 03:19:35 2022] Adding 'vmnet' to the ICE ignore list...
janus_1    | [Mon Jul 18 03:19:35 2022] Selecting local IP address...
janus_1    | [Mon Jul 18 03:19:35 2022] Using 172.19.98.88 as local IP...
janus_1    | [Mon Jul 18 03:19:35 2022] Token based authentication disabled
janus_1    | [Mon Jul 18 03:19:35 2022] Initializing recorder code
janus_1    | [Mon Jul 18 03:19:35 2022] RTP port range: 10000 -- 10500
janus_1    | [Mon Jul 18 03:19:35 2022] Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, half-trickle, IPv6 support disabled)
janus_1    | [Mon Jul 18 03:19:35 2022] ICE port range: 10000-10500
janus_1    | [Mon Jul 18 03:19:35 2022] TURN REST API backend: (disabled)
janus_1    | [Mon Jul 18 03:19:35 2022] [WARN] Janus is deployed on a private address (172.19.98.88) but you didn't specify any STUN server! Expect trouble if this is supposed to work over the internet and not just in a LAN...
janus_1    | [Mon Jul 18 03:19:35 2022] Using certificates:
janus_1    | 	/etc/letsencrypt/live/janus.build110.com/fullchain.pem
janus_1    | 	/etc/letsencrypt/live/janus.build110.com/privkey.pem
janus_1    | [Mon Jul 18 03:19:35 2022] Crypto: BoringSSL
janus_1    | [Mon Jul 18 03:19:35 2022] [FATAL] [dtls.c:janus_dtls_load_keys:331] Error opening certificate file (No such file or directory)
janus_1    | Janus commit: 1c4b1106867ffc4f49a01df02cb785996ca4fa0b
janus_1    | Compiled on:  Tue Jun 21 04:59:10 UTC 2022
janus_1    | 
janus_1    | Logger plugins folder: /usr/local/lib/janus/loggers
janus_1    | [WARN] 	Couldn't access logger plugins folder...
janus_1    | ---------------------------------------------------
janus_1    |   Starting Meetecho Janus (WebRTC Server) v0.12.3
janus_1    | ---------------------------------------------------
janus_1    | 
janus_1    | Checking command line arguments...
janus_1    | [janus.jcfg]
janus_1    |     general: {
janus_1    |         configs_folder: /usr/local/etc/janus
janus_1    |         plugins_folder: /usr/local/lib/janus/plugins
janus_1    |         transports_folder: /usr/local/lib/janus/transports
janus_1    |         events_folder: /usr/local/lib/janus/events
janus_1    |         loggers_folder: /usr/local/lib/janus/loggers
janus_1    |         debug_level: 5
janus_1    |         debug_timestamps: true
janus_1    |         debug_colors: true
janus_1    |         api_secret: uacMZZm7
janus_1    |         admin_secret: Z9A5Z8HUetTpWhV
janus_1    |         protected_folders: [
janus_1    |             /bin
janus_1    |             /boot
janus_1    |             /dev
janus_1    |             /etc
janus_1    |             /initrd
janus_1    |             /lib
janus_1    |             /lib32
janus_1    |             /lib64
janus_1    |             /proc
janus_1    |             /sbin
janus_1    |             /sys
janus_1    |             /usr
janus_1    |             /var
janus_1    |             /usr/local/bin
janus_1    |             /usr/local/etc
janus_1    |             /usr/local/include
janus_1    |             /usr/local/lib
janus_1    |             /usr/local/lib32
janus_1    |             /usr/local/lib64
janus_1    |             /usr/local/sbin
janus_1    |         ]
janus_1    |     }
janus_1    |     certificates: {
janus_1    |         cert_pem: /etc/letsencrypt/live/janus.build110.com/fullchain.pem
janus_1    |         cert_key: /etc/letsencrypt/live/janus.build110.com/privkey.pem
janus_1    |         dtls_accept_selfsigned: true
janus_1    |     }
janus_1    |     media: {
janus_1    |         rtp_port_range: 10000-10500
janus_1    |     }
janus_1    |     nat: {
janus_1    |         nice_debug: false
janus_1    |         ice_ignore_list: vmnet
janus_1    |     }
janus_1    |     plugins: {
janus_1    |     }
janus_1    |     transports: {
janus_1    |     }
janus_1    |     loggers: {
janus_1    |     }
janus_1    |     events: {
janus_1    |     }
janus_1    | Debug/log level is 5
janus_1    | Debug/log timestamps are enabled
janus_1    | Debug/log colors are enabled
janus_1    | [Mon Jul 18 03:20:36 2022] Adding 'vmnet' to the ICE ignore list...
janus_1    | [Mon Jul 18 03:20:36 2022] Selecting local IP address...
janus_1    | [Mon Jul 18 03:20:36 2022] Using 172.19.98.88 as local IP...
janus_1    | [Mon Jul 18 03:20:36 2022] Token based authentication disabled
janus_1    | [Mon Jul 18 03:20:36 2022] Initializing recorder code
janus_1    | [Mon Jul 18 03:20:36 2022] RTP port range: 10000 -- 10500
janus_1    | [Mon Jul 18 03:20:36 2022] Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, half-trickle, IPv6 support disabled)
janus_1    | [Mon Jul 18 03:20:36 2022] ICE port range: 10000-10500
janus_1    | [Mon Jul 18 03:20:36 2022] TURN REST API backend: (disabled)
janus_1    | [Mon Jul 18 03:20:36 2022] [WARN] Janus is deployed on a private address (172.19.98.88) but you didn't specify any STUN server! Expect trouble if this is supposed to work over the internet and not just in a LAN...
janus_1    | [Mon Jul 18 03:20:36 2022] Using certificates:
janus_1    | 	/etc/letsencrypt/live/janus.build110.com/fullchain.pem
janus_1    | 	/etc/letsencrypt/live/janus.build110.com/privkey.pem
janus_1    | [Mon Jul 18 03:20:36 2022] Crypto: BoringSSL
janus_1    | [Mon Jul 18 03:20:36 2022] [FATAL] [dtls.c:janus_dtls_load_keys:331] Error opening certificate file (No such file or directory)

**Comment by h-mdm** [comment]
You have no certificate files. Looks like LetsEncrypt failed to generate certificates and keys for your domain. LetsEncrypt uses port 80 (HTTP) to verify your domain. Make sure the incoming port 80 is available and not occupied by any other application.
