### ISSUE TITLE
COMMUNICATION PROBLEM

### ISSUE THREAD

**Issue by RobsonBreno** [h-mdm/remote-control#42]
HI,
I'VE BEEN TRYING TO CONTACT YOU FOR A FEW MONTHS, AND I'M NOT SUCCESSFUL, I'VE SENT 4 EMAILS... TO TRY TO BUY THE PREMIUM VERSION. BUT YOU NEVER ANSWER.

I UNDERSTAND THAT YOU HAVE 2 WEBSITES? WITH DIFFERENT NAMES?
https://headwind-remote.com/
https://h-mdm.com/

WHICH REAL WEBSITE?
WHY DON'T YOU HAVE A SALES CENTER?
NO PHONE, EMAIL, NOTHING.
WEIRD ..

I REALLY WANT TO BUY, BUT I FEEL INSANE.

**Comment by h-mdm** [comment]
https://h-mdm.com is the open source mobile device management software "Headwind MDM".

https://headwind-remote.com is the open source remote control software "Headwind Remote". This project may be integrated with Headwind MDM.

These are different software projects. Mobile device management is different from the remote control (remote control is actually a part of mobile device management).

I feel sorry that your emails did not reach destination. May I ask you to retry submitting a form on https://h-mdm.com/contact-us/, perhaps by using another contact email?
