### ISSUE TITLE
Custom ports configuration problems

### ISSUE THREAD

**Issue by ll3N1GmAll** [h-mdm/remote-control#44]
Reference - Custom ports configuration #43

I set custom ports in the config.yaml file prior to running the install.sh.

It seems now that the certbot task fails now that nginx is not running on port 80. However, another apache server is running on that VM on port 80. 

Is there a way to change the port that certbot is using by default? 
Is there another certificate option documented instead of certbot?

Also, after adding the variables from deploy/config.defaults.yaml to config.yaml with my custom settings and then running the install.sh, I see no services running on the VM with the ports I set. In fact, nginx doesn't appear to be running at all. Is this all in a docker instance and this is why I am not able to see it? I cannot reach the server from any clients on the custom ports I specified in config.yaml.

**Comment by h-mdm** [comment]
As far as I know, LetsEncrypt always verifies domains by port 80 and you cannot change this behavior. 

Custom certificates are not supported by the free version. In the Premium license, you can use a commercial certificate like Comodo PositiveSSL.

To view logs, cd to the project directory and run the command:

docker-compose logs (module), for example
docker-compose logs nginx

Note that, if certbot doesn't generate a certificate, nginx will not start.
