### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by gusarg81** [h-mdm/remote-control#48]
Hi,

I am installing remot-control on Ubuntu 22.04 (armbian), which is aarch64.

Seems is not supported for janus, because after the installation, the container related to janus is failing because of this:

`janus_1  | exec /usr/local/bin/janus: exec format error`

**Comment by h-mdm** [comment]
You can try building the Janus Docker image from the source code on arm64. The Dockerfile and build instruction is here: https://github.com/h-mdm/remote-control/tree/master/deploy/images/janus-gateway

**Comment by gusarg81** [comment]
Hi,

I've tried and fails with:

> Step 13/20 : COPY --from=BUILD /usr/local/lib/x86_64-linux-gnu/libnice.so.10.12.0 /usr/local/lib/x86_64-linux-gnu/libnice.so.10.12.0
> COPY failed: stat usr/local/lib/x86_64-linux-gnu/libnice.so.10.12.0: file does not exist

**Comment by gusarg81** [comment]
Hi, any ideas about this?

**Comment by h-mdm** [comment]
Headwind Remote currently supports only x86-64 architecture, sorry about that.
