### ISSUE TITLE
Unable to install on Ubuntu 18

### ISSUE THREAD

**Issue by AnishLushte07** [h-mdm/remote-control#50]
Trying to install project using install.sh on ubuntu 18. Getting below error, kindly help.

`TASK [Install python2 pip] *********************************************************************************************************************************
[WARNING]: Updating cache and auto-installing missing dependency: python-apt
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "E: The repository 'http://packages.fluentbit.io/ubuntu xenial Release' does not have a Release file.", "rc": 100, "stderr": "E: The repository 'http://packages.fluentbit.io/ubuntu xenial Release' does not have a Release file.\n", "stderr_lines": ["E: The repository 'http://packages.fluentbit.io/ubuntu xenial Release' does not have a Release file."], "stdout": "Hit:1 https://download.docker.com/linux/ubuntu bionic InRelease\nHit:2 https://download.newrelic.com/infrastructure_agent/linux/apt bionic InRelease\nHit:3 https://deb.nodesource.com/node_10.x bionic InRelease\nHit:4 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu bionic InRelease\nGet:5 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]\nHit:6 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease\nHit:7 http://ppa.launchpad.net/ansible/ansible/ubuntu bionic InRelease\nHit:8 http://security.ubuntu.com/ubuntu bionic-security InRelease\nGet:9 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]\nHit:10 http://nsolid-deb.nodesource.com/nsolid_3.x bionic InRelease\nHit:12 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic InRelease\nHit:13 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease\nIgn:14 https://download.konghq.com/gateway-2.x-ubuntu-bionic default InRelease\nIgn:11 https://packages.fluentbit.io/ubuntu xenial InRelease\nErr:16 https://packages.fluentbit.io/ubuntu xenial Release\n  404  Not Found [IP: 139.178.85.103 443]\nHit:15 https://download.konghq.com/gateway-2.x-ubuntu-bionic default Release\nIgn:17 https://download.konghq.com/gateway-2.x-ubuntu-bionic default Release.gpg\nReading package lists...\n", "stdout_lines": ["Hit:1 https://download.docker.com/linux/ubuntu bionic InRelease", "Hit:2 https://download.newrelic.com/infrastructure_agent/linux/apt bionic InRelease", "Hit:3 https://deb.nodesource.com/node_10.x bionic InRelease", "Hit:4 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu bionic InRelease", "Get:5 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]", "Hit:6 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease", "Hit:7 http://ppa.launchpad.net/ansible/ansible/ubuntu bionic InRelease", "Hit:8 http://security.ubuntu.com/ubuntu bionic-security InRelease", "Get:9 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]", "Hit:10 http://nsolid-deb.nodesource.com/nsolid_3.x bionic InRelease", "Hit:12 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic InRelease", "Hit:13 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease", "Ign:14 https://download.konghq.com/gateway-2.x-ubuntu-bionic default InRelease", "Ign:11 https://packages.fluentbit.io/ubuntu xenial InRelease", "Err:16 https://packages.fluentbit.io/ubuntu xenial Release", "  404  Not Found [IP: 139.178.85.103 443]", "Hit:15 https://download.konghq.com/gateway-2.x-ubuntu-bionic default Release", "Ign:17 https://download.konghq.com/gateway-2.x-ubuntu-bionic default Release.gpg", "Reading package lists..."]}`

**Comment by h-mdm** [comment]
This seems to be an Ubuntu configuration issue. 

Here are related articles:
https://askubuntu.com/questions/866901/what-can-i-do-if-a-repository-ppa-does-not-have-a-release-file
https://stackoverflow.com/questions/62487616/ubuntu-xenial-release-no-longer-has-a-release-file-error-in-ubuntu
