### ISSUE TITLE
he client fails to connect to the serve

### ISSUE THREAD

**Issue by liujie12** [h-mdm/remote-control#53]
Every 1 to 2 months, the client fails to connect to the server, and the server recovers after restarting. This has happened twice. the following information is displayed on the client: Session error Error connecting to any of the provided janusservers is ne server Gown!

**Comment by h-mdm** [comment]
The most probable origin of the issue is the expiration of the LetsEncrypt certificate.

The workaround is to add the following script in the weekly cron job:

/path/to/headwind-remote/letsencrypt-ssl-renew.sh

(replace /path/to/hadwind-remote/ with the real path on your server).
