### ISSUE TITLE
headwin remote don't finised to setup

### ISSUE THREAD

**Issue by ErnestoAbram** [h-mdm/remote-control#55]
Hello, I am tryng to setup a headwin in a VM in google cloud. My machine have 2cpu and 4G, plus 25gb HD.
I get to install in this machine, but when I try to connect, I get ha page with a setup text in first plane with a circular progress bar.

I try to restart the system, but it don't change.

In the movil app, with the correct url , neither work.

**Comment by h-mdm** [comment]
Most probable reason is that port 8989 is closed. Make sure all ports listed at https://headwind-remote.com/installation/ are opened on the firewall.

To get more details, please open Chrome developer console (... -> More tools -> Developer tools, Network tab) and check which request is pending.

**Comment by ErnestoAbram** [comment]
Thanks!.
