### ISSUE TITLE
npm Error [ERR_REQUIRE_ESM]:

### ISSUE THREAD

**Issue by guyacamole** [h-mdm/remote-control#58]
web-admin dont up
`
  Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /app/node_modules/gulp-size/index.js
  require() of ES modules is not supported.
  require() of /app/node_modules/gulp-size/index.js from /app/gulpfile.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
  Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /app/node_modules/gulp-size/package.json.

    at new NodeError (node:internal/errors:277:15)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1119:13)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/app/gulpfile.js:7:12)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32) {
  code: 'ERR_REQUIRE_ESM'
}
`
and web just show 
![Screenshot from 2023-11-14 14-18-12](https://github.com/h-mdm/remote-control/assets/93730346/c211d432-1466-4e66-ba77-73e6d57de484)

this happend to me every time y tried to run node-gulp-builder-container
'
  OS:
  'NAME="Ubuntu"
  VERSION="20.04.6 LTS (Focal Fossa)"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 20.04.6 LTS"
  VERSION_ID="20.04"
  HOME_URL="https://www.ubuntu.com/"
  SUPPORT_URL="https://help.ubuntu.com/"
  BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  VERSION_CODENAME=focal
  UBUNTU_CODENAME=focal
'

**Comment by GabLeRoux** [comment]
Same problem here, fresh install using provided https://github.com/h-mdm/remote-control/blob/master/install.sh. Getting 403 Forbidden.

Logs in docker-compose don't help much, but the generated app in `web-admin` seem quite empty. I'm suspecting a failure to build the app, but in my case, logs aren't shown as it's running from ansible.

I'll look for details tomorrow.

**Comment by guyacamole** [comment]
i think is a problem with the build of web-admin, wen a run 
'./install.sh' 
takes to much in one step and give me the next error
`TASK [Waiting until web-admin is ready] ********************************************************************************************************************************************************************





fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for file ../web-admin/dist/js/app.min.js"}

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=53   changed=14   unreachable=0    failed=1    skipped=45   rescued=0    ignored=0  `

**Comment by h-mdm** [comment]
Please pull latest changes from the repository and restart Headwind Remote from scratch, the issue should be fixed now.

**Comment by GabLeRoux** [comment]
I confirm ed7f315 fixed this issue, thanks for the quick response 👍
