### ISSUE TITLE
ssl  http://*/.well-known/acme-challenge/*  Fetching

### ISSUE THREAD

**Issue by spatxos** [h-mdm/remote-control#60]
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "case \"true\" in\n  \"true\") eff_arg=\"--eff-email\" ;;\n  \"false\") eff_arg=\"--no-eff-email\" ;;\nesac\nexport PATH=$PATH:/usr/local/bin\ndocker-compose -f ./../docker-compose.yaml run --rm --entrypoint \"\\\n  certbot certonly -n --webroot -w /var/www/certbot \\\n    --email 670526967@qq.com \\\n    $eff_arg\n    -d remotecontrol.host.com \\\n    --rsa-key-size 4096 \\\n    --agree-tos\" certbot\n", "delta": "0:00:32.301216", "end": "2024-02-01 15:59:31.132199", "msg": "non-zero return code", "rc": 1, "start": "2024-02-01 15:58:58.830983", "stderr": " Container remote-control_nginx_1  Recreate\n Container remote-control_nginx_1  Recreated\n Container remote-control-nginx-1  Starting\n Container remote-control-nginx-1  Started\nSaving debug log to /var/log/letsencrypt/letsencrypt.log\nPlugins selected: Authenticator webroot, Installer None\nObtaining a new certificate\nPerforming the following challenges:\nhttp-01 challenge for remotecontrol.host.com\nUsing the webroot path /var/www/certbot for all unmatched domains.\nWaiting for verification...\nChallenge failed for domain remotecontrol.host.com\nhttp-01 challenge for remotecontrol.host.com\nCleaning up challenges\nSome challenges have failed.", "stderr_lines": [" Container remote-control_nginx_1  Recreate", " Container remote-control_nginx_1  Recreated", " Container remote-control-nginx-1  Starting", " Container remote-control-nginx-1  Started", "Saving debug log to /var/log/letsencrypt/letsencrypt.log", "Plugins selected: Authenticator webroot, Installer None", "Obtaining a new certificate", "Performing the following challenges:", "http-01 challenge for remotecontrol.host.com", "Using the webroot path /var/www/certbot for all unmatched domains.", "Waiting for verification...", "Challenge failed for domain remotecontrol.host.com", "http-01 challenge for remotecontrol.host.com", "Cleaning up challenges", "Some challenges have failed."], "stdout": "IMPORTANT NOTES:\n - The following errors were reported by the server:\n\n   Domain: remotecontrol.host.com\n   Type:   connection\n   Detail: 11.111.111.111: Fetching\n   http://remotecontrol.host.com/.well-known/acme-challenge/KdVqhWQrnaDmATbqeCar33xqR1eq9joVjIEp6LsTc_I:\n   Timeout during connect (likely firewall problem)\n\n   To fix these errors, please make sure that your domain name was\n   entered correctly and the DNS A/AAAA record(s) for that domain\n   contain(s) the right IP address. Additionally, please check that\n   your computer has a publicly routable IP address and that no\n   firewalls are preventing the server from communicating with the\n   client. If you're using the webroot plugin, you should also verify\n   that you are serving files from the webroot path you provided.\n - Your account credentials have been saved in your Certbot\n   configuration directory at /etc/letsencrypt. You should make a\n   secure backup of this folder now. This configuration directory will\n   also contain certificates and private keys obtained by Certbot so\n   making regular backups of this folder is ideal.", "stdout_lines": ["IMPORTANT NOTES:", " - The following errors were reported by the server:", "", "   Domain: remotecontrol.host.com", "   Type:   connection", "   Detail: 11.111.111.111: Fetching", "   http://remotecontrol.host.com/.well-known/acme-challenge/KdVqhWQrnaDmATbqeCar33xqR1eq9joVjIEp6LsTc_I:", "   Timeout during connect (likely firewall problem)", "", "   To fix these errors, please make sure that your domain name was", "   entered correctly and the DNS A/AAAA record(s) for that domain", "   contain(s) the right IP address. Additionally, please check that", "   your computer has a publicly routable IP address and that no", "   firewalls are preventing the server from communicating with the", "   client. If you're using the webroot plugin, you should also verify", "   that you are serving files from the webroot path you provided.", " - Your account credentials have been saved in your Certbot", "   configuration directory at /etc/letsencrypt. You should make a", "   secure backup of this folder now. This configuration directory will", "   also contain certificates and private keys obtained by Certbot so", "   making regular backups of this folder is ideal."]}

dns resolution is successful.
![image](https://github.com/h-mdm/remote-control/assets/29770198/7e1cf8c0-f76d-4615-a504-0a668a5e43a7)
![image](https://github.com/h-mdm/remote-control/assets/29770198/ab880cc6-e393-4d77-b42e-b17b888306de)

**Comment by h-mdm** [comment]
To validate the domain, LetsEncrypt uses port 80 (plain HTTP). Make sure this port is opened on the firewall, and no application (like Apache or Nginx) is occupying the port 80 on the server.

**Comment by spatxos** [comment]
The approximate reason has been found. It may be because servers purchased in mainland China require domain names to be registered with the Ministry of Industry and Information Technology. Unregistered domain names will be redirected to the specified page with 302, resulting in LetsEncrypt not successfully issuing the certificate. It is not a problem that port 80 of the server is occupied.
